#!/usr/bin/env python3
"""rebuild_playlist.py — regenerate history/playlist.js from the directory.

Scans `<world>/history/` for `*.html` files (excluding `index.html`),
sorts them chronologically (filenames start with ISO timestamps), and
writes a fresh `playlist.js` so the timelapse player picks up every
archived frame on disk — even ones the agent forgot to register or that
were dropped in by hand.

Behavior:
  - Existing `playlist.js` is REPLACED. (A backup is saved as
    `playlist.js.bak` next to it.)
  - Notes from the previous `playlist.js` are preserved when the
    matching filename still exists.
  - Frames with no recoverable note get an empty `note: ""`.

Usage:
  python tools/rebuild_playlist.py                     # default world
  python tools/rebuild_playlist.py --world <path>      # explicit world
  python tools/rebuild_playlist.py --dry-run           # show plan, no write

Resolves the default world from $HOME / %USERPROFILE% + /.claude/zergling-world/.
"""
from __future__ import annotations
import argparse
import os
import re
import sys
from pathlib import Path


# ISO-ish timestamp prefix: 2026-05-23T14-42-34Z (we allow trailing _slug.html)
TS_RE  = re.compile(r"^(\d{4}-\d{2}-\d{2}T\d{2}-\d{2}-\d{2}Z)(?:_[^.]*)?\.html$")
ENTRY_RE = re.compile(
    r"""window\.playlist\.push\s*\(\s*\{\s*
        file\s*:\s*["']([^"']+)["']\s*,\s*
        ts\s*:\s*["']([^"']+)["']\s*
        (?:,\s*note\s*:\s*["'](?P<note>(?:[^"'\\]|\\.)*)["']\s*)?
    \}\s*\)\s*;?""",
    re.VERBOSE,
)


def default_world() -> Path:
    home = Path(os.environ.get("USERPROFILE") or os.environ.get("HOME") or "")
    return home / ".claude" / "zergling-world"


def parse_existing_notes(playlist_path: Path) -> dict[str, str]:
    """Read existing playlist.js and map filename -> note (best effort)."""
    if not playlist_path.is_file():
        return {}
    notes: dict[str, str] = {}
    text = playlist_path.read_text(encoding="utf-8", errors="replace")
    for m in ENTRY_RE.finditer(text):
        fname = m.group(1)
        note  = m.group("note") or ""
        # un-escape backslash sequences we'll have to re-escape on write
        note = note.replace('\\"', '"').replace("\\'", "'").replace("\\\\", "\\")
        notes[fname] = note
    return notes


def ts_from_filename(fname: str) -> str | None:
    m = TS_RE.match(fname)
    if not m:
        return None
    raw = m.group(1)  # 2026-05-23T14-42-34Z
    # restore : in the time portion
    date_part, time_part = raw.split("T")
    time_part = time_part.rstrip("Z").replace("-", ":")
    return f"{date_part}T{time_part}Z"


def escape_js_string(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--world", type=Path, default=None,
                    help="path to zergling-world (default: ~/.claude/zergling-world)")
    ap.add_argument("--dry-run", action="store_true",
                    help="print the plan; do not write playlist.js")
    args = ap.parse_args()

    world = (args.world or default_world()).resolve()
    history = world / "history"
    if not history.is_dir():
        sys.exit(f"error: no history directory at {history}")

    playlist_path = history / "playlist.js"
    backup_path   = history / "playlist.js.bak"

    notes = parse_existing_notes(playlist_path)
    print(f"world:    {world}")
    print(f"history:  {history}")
    print(f"existing playlist entries: {len(notes)}")

    frames: list[tuple[str, str]] = []  # (filename, ts)
    skipped: list[str] = []
    for entry in sorted(history.iterdir()):
        if not entry.is_file() or entry.suffix.lower() != ".html":
            continue
        if entry.name == "index.html":
            continue
        ts = ts_from_filename(entry.name)
        if ts is None:
            skipped.append(entry.name)
            continue
        frames.append((entry.name, ts))

    # sort by ts (which sorts the same as filename for ISO format)
    frames.sort(key=lambda fn_ts: fn_ts[1])

    print(f"frames found on disk: {len(frames)}")
    if skipped:
        print(f"skipped (no ISO timestamp prefix): {len(skipped)}")
        for s in skipped:
            print(f"  - {s}")

    if not frames:
        print("nothing to write.")
        return 0

    lines = [
        "// zergling-world timelapse playlist",
        "// Auto-generated by tools/rebuild_playlist.py — safe to overwrite.",
        "// Each frame on disk is listed once; notes are preserved across rebuilds.",
        "",
        "window.playlist = window.playlist || [];",
        "",
    ]
    for fname, ts in frames:
        note = notes.get(fname, "")
        lines.append(
            f'window.playlist.push({{ file: "{escape_js_string(fname)}", '
            f'ts: "{ts}", note: "{escape_js_string(note)}" }});'
        )
    new_content = "\n".join(lines) + "\n"

    if args.dry_run:
        print("\n--- dry run; would write: ---")
        print(new_content[:600] + ("\n... (truncated)" if len(new_content) > 600 else ""))
        return 0

    if playlist_path.is_file():
        backup_path.write_bytes(playlist_path.read_bytes())
        print(f"backed up old playlist -> {backup_path}")

    playlist_path.write_text(new_content, encoding="utf-8")
    print(f"wrote {len(frames)} entries -> {playlist_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
